### ISSUE TITLE
crash can't start application 

### ISSUE THREAD

**Issue by bluelovers** [Zicore/TradingPostNotifier#13]
no anyother message

**Comment by Zicore** [comment]
Try to go to %appdata%\ZicoresTradingPostNotifier and rename the config.xml.

**Comment by bluelovers** [comment]
lol, thx it work

**Comment by bluelovers** [comment]
how can i show my tp item, like old version?

**Comment by Zicore** [comment]
Thats currently not possible. Sorry.
