### ISSUE TITLE
i search "shadow" but didn't show new item

### ISSUE THREAD

**Issue by bluelovers** [Zicore/TradingPostNotifier#16]
i search "shadow" but didn't show new item

**Comment by Zicore** [comment]
What Item do you want to find?

**Comment by bluelovers** [comment]
new dye, new weapen skin

**Comment by Zicore** [comment]
I probably know what's going on there. I check it this weekend.

**Comment by Zicore** [comment]
The local Database is out of date. I just fetched the most recent items. Download them here http://upppor.it/aofgltdw.zip and replace the item_xx.json files in the DB Folder.
It's now also described in the Readme.md.
