### ISSUE TITLE
[Suggestion] Guide to manually update the DB

### ISSUE THREAD

**Issue by SeppDE** [Zicore/TradingPostNotifier#17]
Hey there Zicore,

any chance that you can post an quick guide how to update the .json files in the DB manually?

Could be helping people to use you're tool with all the updates all around.

Greetings

**Comment by Zicore** [comment]
I'll give it a look. I made a tool which generates the DBs. I can probably integrate it to the notifier.

**Comment by bluelovers** [comment]
need new item db for hot pls
